### ISSUE TITLE
CLI: solve a facelet state

### ISSUE THREAD

**Issue by vmiklos** [luckasRanarison/kewb#5]
Hi,

Would you accept a PR to have a (let's say) `cargo run -- solve -f <facelet string>` CLI interface, that would allow solving a state not by providing the scramble but by providing a facelet string?

Thanks.

**Comment by luckasRanarison** [comment]
Yes, that sounds good to me. I'm looking forward to it :)

**Comment by luckasRanarison** [comment]
By the way, I wanted to include you in the `authors` but I don't know what name should I use.

**Comment by vmiklos** [comment]
It's in the git log or github profile, `Miklos Vajna <vmiklos@vmiklos.hu>` :)
